apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: zioduck/test-server
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: node-server
spec:
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-server
  annotations:
    konghq.com/plugins: oidc
spec:
  ingressClassName: kong
  rules:
  - host: node.localhost.com
    http:
      paths:
      - backend:
          service:
            name: node-server
            port:
              number: 4000
        path: /
        pathType: ImplementationSpecific